FuelRats/pipsqueak3

.codeclimate.yml, setup.cfg
Update the build configurations to enable Code Climate.
the setup.cfg is for pep8 style checking, the modifications, `.codeclimate.yml` is to set the python language to py 3, as it defaults to python2.
=> Merge CI configuration changes

.travis.yml
This PR changes the test environment from the `unittest` framework to `pytest`
The `pyTest` framework appears to be far better suited for our Test Driven Development than `unittest`, and it requires far less effort to create new tests.
`PyTest` also includes many more features that we may be able to leverage to increase the quality of our tests without greatly increasing complexity and overhead.
PyTest will run `unittest` tests, so it is plug and play, and does not require any modification to existing tests to make use of.
=> Change Travis to use PyTest as the test runner

Modules/rat_rescue.py, ratlib/names.py, tests/conftest.py, tests/test_rescue.py
This PR implements the `Rescue.status` property and its Setter.
This property returns an instance of the `Status` enum, which i placed in `ratlib\names.py`
The Status enum includes three states:
`OPEN` case is open and active
`CLOSED` case is marked as closed
`INACTIVE` case is marked as open and inactive
The `Rescue.is_open` property has been renamed `rescue.open` and has been reimplemented to make use of the `Rescue.status` property. The `rescue._open` attribute has been removed.
the `Rescue.inactive` property has been reimplemented to use `Rescue.status` property.
the attribute `Rescue._inactive` has been removed.
=> Implement Rescue.status

Modules/rat_rescue.py, Modules/rats.py, tests/conftest.py, tests/test_Rats.py, tests/test_rescue.py
This PR adds a method `Rats.get_rat_from_uuid` and refactors `Rats.get_rat` into `Rats.get_rat_by_name`
Both methods are now async due to the API calls, associated tests have been updated respectively.
Both new functions will first check their respective client-side Rats class attribute caches and, in the event of a cache miss, make an API query (TODO: requires API interface) to fetch the rat from the API.
This PR also Adds `Rats.__eq__`, and fixes a couple elusive bugs in Rats and their associated tests. `RatGood_fx` now uses hard-coded UUIDs to remove randomness from that part of the test suite, this helped simplify debugging of a bigger problem (which is why I implemented a `Rats.__eq__` method.)
Further, the scope of `RatGood_fx` has been lowered back to test level, as the underlying …
=> Implement ability to fetch a rat by uuid alone

Modules/permissions.py, Modules/trigger.py, tests/test_permissions.py, tests/test_trigger.py
This PR implements `__hash__` methods for the Trigger and Permission objects.
It also implements an `__eq__` method for the Trigger object and makes both objects relatively immutable.
The Trigger object's `__hash__` simply xors the hashes of its key attributes together, but it only does it once when the hash is first needed. The Permission's `__hash__` just uses the permission level to be in line with its `__eq__` method.
I likely won't give the API handlers `__eq__` and `__hash__` methods because, on seconds thought, that's pretty fucking pointless.
=> Make Trigger and Permission objects hashable and more or less immutable (SPARK-12)

.dockerignore, Docker.md, Dockerfile, docker-compose.yml
This PR enables the ability for Mecha to run within a Docker Container.
Specifically, mecha3's container is build off Alpine Linux, a minimalistic Linux distribution.
The only things added to it are Git, Mecha's codebase, and her dependencies.
Docker will allow us to have a uniform testing environment, outside what Travis provides. Further, It is to my understanding mecha3 may end up running within a container when she goes live. This facilitates that intention. 
Trezy, asking you to review things as you have Docker experience more than I, please let me know if you spot something obviously flawed with my approach 😄
=> Enable Docker Support

Modules/mark_for_deletion.py, Modules/rat_rescue.py, tests/test_rescue.py
This PR reimplements `Rescue.mark_for_deletion`, giving it its own data structure `MarkForDelete`.
Most of our complex data structures now exist as Class objects, such as `User`, `Rats`, and `Quotation`.
Therefore, i reason, it is about time we do the same for MarkForDeletion.
Doing it this way better separates the API from Mecha's runtime, as the API would be able to change the background structure of the object without requiring significant change to Mechasqueak itself, but rather its API driver. 
This change also contributes to documentation and ease-of development as many IDEs find it easier to provide completions for Class objects than for dictionary entries.
Introduced class:
----------------
`MarkForDelete`
`marked`: bool, indicates if the rescue is marked for deletion
`reporter`: …
=> SPARK-30: MarkForDeletion object

Modules/mark_for_deletion.py, tests/conftest.py, tests/test_mark_for_deletion.py, tests/test_rescue.py
this PR implements the missing `MarkForDeletion.__eq__` method.
As a supplement, i have also implemented a `__hash__` method for this object.
=> SPARK-39: MD `__eq__` and `__hash__` methods

.circleci/config.yml
This PR simply adds the `--doctest-modules` cli flag to the circleci test command.
=> SPARK-40: Include doctests in tests

Modules/permissions.py, commands/debug.py, tests/test_permissions.py
This was a bit of a doozy.
As described in SPARK-53 there was a bug that required the `@require_channel` and `@require_dm` to be used as follows:
```py
@require_channel()
async def my_command(...)
```
the empty `()` being an anoying requirement. This PR fixes that.
the valid usages for the decorators has been corrected, can can be used in either of the following forms
```py
@require_channel
async def my_command(...)
```
which will use the default access denied message.
```py
@require_channel(message="Heck no.")
async def my_command(...)
```
The kwarg **must be specified**, if the kwarg is not specified it will be ignored and the function may be have unexpectidly. 
Fixes SPARK-53
=> SPARK-53 fix silly @require_channel decorator requirement

tests/test_ratlib.py, utils/ratlib.py
This Pr implements a Singleton base class that is not a metaclass.
Being a base class, it has the benefit that classes inheriting `Singleton` can use other metaclasses, such as `abc.ABCMeta` or `typing.Generic`.
The `Singleton` class will add the attribute `cls._instance` to all child classes,
this class attribute is where Singleton stores the single instance of the child class when it is first instantiated.
=> Implement a Singleton

Modules/rat.py, Modules/rat_cache.py, Modules/rat_rescue.py, tests/test_rats.py, utils/ratlib.py
`Platforms.DEFAULT` nolonger exists as requested. `None` may replace its usages
=> Culled Platforms.DEFAULT, allowed usage of None in its place

tests/conftest.py, tests/test_logging.py
As requested, this is a change to the string verification side of the logging tests, so that tests using xdist won't error out due to an inconsistent file IO issue.  No changes to production code on the mecha side included, this is testing only.
=> Logging Fixture change (Testing)

Modules/permissions.py, Modules/rat_command.py, Modules/rules.py, main.py, tests/conftest.py, tests/mock_callables.py, tests/mocks.py, tests/test_rat_command.py, tests/test_rules.py
This PR implements SPARK-55 and the SPARK-54, which it requires. It also implements SPARK-56.
It adds a `pass_match` parameter to the rule decorator to implement SPARK-55. It also adds a parameter for toggling case-sensitivity as well as one to switch whether the regex should match the entire message (minus the prefix on non-prefixless rules, see below) or just the first word (for command-like rules).
SPARK-56's prefixless rules are also implemented. This did, however, need some doing in the command triggering logic: `MechaClient.on_message` now only checks that the message does not come from Mecha itself. `rat_command.trigger` tries to find a command, a regular old rule or a prefixless rule, in that order. If it can't find anything, it returns, possibly logging a warning. These changes …
=> SPARK-54, SPARK-55 and SPARK-56: Rule decorator improvements

main.py
This PR makes the following changes:
* Rewriting startup to happen in a coroutine.
* Remove the use of `ClientPool`, instead using `client.connect(...)` directly.
Functionality should have stayed the same. In fact, apart from the minor changes in logging during startup, one shouldn't be able to tell that anything changed.
=> SPARK-66: Clean up startup code and move it into a coroutine

tests/conftest.py, tests/mock_bot.py
This PR makes the `MockBot` class a subclass of the `MechaClient`.
The primary motivation here is to enable the usage of the mock bot's overriden methods while calling methods on the MechaClient instance. For instance, in SPARK-50 i need to call Mechaclient methods to verify their function, which in turn call methods overriden in MockBot. For these tests, i am testing the implementation of the Mechaclient method, not the pydle back end. Therefore being able to easily mock out the `whois` method is of value.
Since the MockBot is provided as a facility to mock certain Mechaclient calls for the sake of testing, it makes sense to have it simply extend and override the corresponding methods in the Mechaclient.
This change does not break existing tests, nor requires any rework of them.
This …
=> Make the MockBot a subclass of the MechaClient

tests/mock_callables.py
`CallableMock` now take an optional constructor parameter `function_to_mimic`. Nothing will change for instances without this parameter set.
If it is set, however, the `_bound_calls` field will hold a list of `inspect.BoundArguments` instances, one for each call. These can be accessed via the property `CallableMock.bound_calls` and is also considered by `was_called_with`.
From the `CallableMock` docstring:
```rest
Additionally, a :class:`CallableMock` can be made to mimic an existing function or method, such
that args and kwargs can be matched to the arguments that the function expects. This also works
with many other callables including bound methods, but may fail for certain built-in functions
and methods.
Note that calling a mock mimicking a function will raise a :exc:`TypeError` if …
```
=> SPARK-69 & SPARK-72: Allow CallableMock to mimic an existing callable's signature and to raise a previously set exception

Modules/context.py, pytest.ini, tests/regressions/test_context_regressions.py
This PR resolves SPARK-71 by correcting Context's prefix processing.
Context will now only strip exactly the command prefix from the start of the message leaving any subsequent characters (such as the command-prefix being used improperly)
This PR also adds a test module for regression tests, which can be used to house further regression tests as more bugs are detected and fixed.
Further, I have added a pytest marker for regression tests, so they can be run independently from the rest of the test suite.
End result: if our command prefix is `!`, commands such as `!bang` will now behave as expected, 
```
<unknown> !!bang
<Mechasqueak3-tests[BOT]> boom!
<unknown> good.
```
=> SPARK-71 Fixed faulty command prefix processing in Context

config.py
Resolves SPARK-70
Default encoding does not properly support "extended characters" which can lead to undocumented behavior in mecha3 relating to config file contents.
The solution is as simple as specifying UTF8 as the file format during the open() call.
=> SPARK-70 Open the config file with UTF8 encoding

Modules/rat_rescue.py, tests/test_rat_board.py, tests/test_rescue.py
Allow Rescue be created via a default constructor.
Resolves SPARK-68.
All fields are now nullable, and System can now be safely set to None as needed.
=> SPARK-68 Allow Rescue to have a Default constructor

pytest.ini
Apparently Pydle's test suite gets detected by PyTest in some configurations, which leads to bad things.
I added a line to the `pytest.ini` configuration file as to manually specify our `tests/` directory as the test discovery root. This prevents pytest from trying to run dependencies' test suite(s).
=> [Testing/bugfix]Manually specify our testing directory

main.py
mistooks were made.
We should not be passing the original message into context creation, but the sanetitized version.
Presently we sanetrize the message but discard the result erroneously. this pr fixes that
=> SPARK-80 Use the sanitized message object for context creation 

.coveragerc
The `utils` directory was never added to our code coverage, which was causing a warning to appear during coverage testing. This simple fix adds `utils` into `.coveragerc`.
Note that `utils/ratlib.py` currently has a coverage of 91%, so this may change may drop overall coverage slightly.
=> Add the 'utils' directory to coverage reports

tests/test_ratlib.py, utils/ratlib.py
Fixes SPARK-73.
This rewrites the regular expression that filters out IRC control codes, and now includes every control code I could find. Including bold, italic, underline, strikethrough, monospace, color, hex color, reverse color, and reset.
This also removes the unnecessary stripping of semicolons from IRC messages, and it will now filter tabs from messages.
=> Adjust sanitize to filter tabs and IRC control codes

.circleci/config.yml, Modules/user.py, Pipfile, Pipfile.lock, pylint.ini, tests/test_user.py
This PR adds Pylint to our CI build, with the end goal of removing CodeClimate from the build system.
Rational
-------------
Im not the biggest fan of CodeClimate, i find its interface hard to use at the best of times and configuring its linting rules to be a PITA at the worst of times. 
Further, i find its inspections lacking insight, and is relatively inflexible. 
Instead, I introduce pylint into the mix to cover the linting rules. It is a well maintained and widely used QA tool in python, and boasts a wide array of options, inspections, and other utilities that may prove useful. Further, unlike codeclimate, Pylint can be run locally with consistent results. 
We use CodeClimate for a QA pass, specifically for linting and asserting code coverage. 
Pylint appears to be superior in terms …
=> Integrate pylint into CI build (take II)

Pipfile, Pipfile.lock, tests/test_rescue.py
`pytest-asyncio` has released version 0.10.0, which fixes the incompatibility introduced when `pytest` updated to 4.1.0. We can now unpin these dependencies.
=> Unpin pytest, as pytest-asyncio has updated

tests/galaxy/conftest.py
According to [the documentation of werkzeug](http://werkzeug.pocoo.org/docs/0.14/serving/#troubleshooting), some later \*nix and Windows machines struggle to use `localhost` as a hostname, because they attempt to use IPv6 first, fail, then fall back on IPv4.
This caused the test suite of `Galaxy` to run upwards of 20 seconds on Windows platforms. To fix this issue, I've adjusted the mock server to use an IPv4 address explicitly, thus overcoming the issue of IPv6 resolution.
=> Speed up Galaxy's testing on Windows

database/database_manager.py, pytest.ini, tests/conftest.py
fixes reconfiguration introduced in #73 that caused doctests for modules not to execute.
An unfortunate side-effect of specifying the starting directory for test discovery, pointing it at a directory outside our Module space, is that doctests are not discovered in the module space. The lack of discovery, therefore, means they will not be run.
Edit: its worth noting the original impetus for #73 is resolved by us now using the normal pydle distribution.
=> Fixes doctest misconfiguration

.github/CODEOWNERS
This PR adds a `CODEOWNERS` configuration file to the project.
This file defines who is automatically requested / required to approve a pull request based on the files that have been changed.
I have assigned codeowners based on which parts of the project each member is assigned to, hopefully everyone finds the configuration acceptable. If not, feel free to yell at me.
anything in `/docs/`, as well as `/database/` and `Modules/fact_manager.py` have been assigned to @shatteredbeam 
Anything in `/Galaxy/` is assigned to @Eearslya 
Rules are assigned to @MHajoha , and the API module will be as well once merged.
I have assigned myself to anything not otherwise claimed, as well as explicitly claiming the various CI configuration files.
In theory this is just a formalization, rather than a …
=> Add CODEOWNERS configuration file

Modules/rat_rescue.py
Adds `platform` to Rescue's constructor with a default value of `None`.
=> Add platform to Rescue's constructor

Modules/galaxy/galaxy.py, tests/galaxy/conftest.py, tests/galaxy/test_galaxy.py
For SPARK-95.
This adds a new method to `Galaxy`, `find_nearest_landmark`. Given an existing `StarSystem` object, it will find the nearest system out of a hardcoded list of "landmark" star systems. This will help to provide location context for things like rescue announcements (the `(158ly from Sol)` part, specifically.)
=> Add find_nearest_landmark method to Galaxy
